### ISSUE TITLE
Quick Fix dialog doesn't show up

### ISSUE THREAD

**Issue by indev-aj** [BendixMa/Dart-Data-Class-Generator#12]
Hello, I was following a tutorial on youtube which uses this extension. So, I was supposed to press `Ctrl + .` to bring the dialog, but when I did it, it shows `no code action available`. Currently on version 0.3.17

**Comment by BendixMa** [comment]
Can you please provide a code sample for the class you want to generate from?

**Comment by indev-aj** [comment]
```
class Email {
  final String value;

  const Email(this.value) : assert(value != null);
}
```

**Comment by BendixMa** [comment]
Its working for me just fine. Note that the generator wont show the quickfix dialog when the cursor is on the empty line though.

**Comment by indev-aj** [comment]
Apparently, after I restarted my pc it works just fine. Thanks
