### ISSUE TITLE
Doesn't work if field contains "class" word

### ISSUE THREAD

**Issue by rimidalv** [BendixMa/Dart-Data-Class-Generator#2]
For example: 
if class contains next:

final String classifire; 

The plugin doesn't work. But if i change the field name to clazsifire or to other name without class - all works good.

**Comment by BendixMa** [comment]
Hey thanks for letting me know. Indeed when there is the word "class" in a line, the plugin thinks that a new class is being declared and thus the generator stops working. I'll fix it in the coming days when I have time to spare. For now, as you've said, just use a different name and then rename the variable afterwards.

**Comment by BendixMa** [comment]
I released a new version `(0.3.2)` that should fix this issue.
