### ISSUE TITLE
some problem: #7

### ISSUE THREAD

**Issue by huang12zheng** [BendixMa/Dart-Data-Class-Generator#8]
some problem:
1. 
```
UserSetting:  Dart_data_class_generator: Equality
If true, generates a value equality function for a data class.
```
is trouble with reminding.Since We have a Setting EquableMixin

 it is need to add a remark like
 `it is override operator ==`

2. I use ToolClass #4 
```dart
abstract class ModelBase with EquatableMixin{
  Map<String, Object> toMap();
  String toJson() => json.encode(toMap());
  copyWith();
  String toString() => '$runtimeType ${toJson()}';
}
```
it is not adaptive to you code

in detail,
```dart
class C extends ModelBase {
  int a;
  int b;
}
```
=>
```dart
class C extends ModelBase with EquatableMixin {
  int a;
  int b;
...
}
```

**Comment by BendixMa** [comment]
In regards to 1): I agree that this is more expressive and I'll change it.  

In regards to 2: The generator of course only uses very superficial metrics to generate data classes and has no awareness whatsoever about the class hierarchy of a data class and so there is no way for the generator to know that `ModelBase` already extends `EquatableMixin`. We would have to make much more comprehensive analysis of the classes in a project which is probably out of the scope for this little extension. This is also very specific to your implementation and I guess you will have to live with it and remove the `with EquatableMixin` whenever you run the generator or write your data classes again by hand.

**Comment by huang12zheng** [comment]
I don't think it is necessary to must generate `with mixin`, it could be a switcher seted by  user?
or just spliced the `SuperClass`,which is seted by user.

**Comment by BendixMa** [comment]
Most base classes for models do also have the word `Base` in their name (as with `ModelBase`). We could check if the name of the superclass contains the word `Base` and if it does, we don't generate the mixin. Otherwise I think there is no reason not to generate the mixin as model classes usually don't have a deep class hierarchy.

**Comment by huang12zheng** [comment]
```js
if (clazz.hasSuperclass && !clazz.superclass.includes('Base')) {
```
it is some problem. I think it is more good as follow 
```js
 if (!clazz.hasSuperclass || !clazz.superclass.includes('Base')) {
            this.requiresImport('package:equatable/equatable.dart');
            this.addMixin('EquatableMixin');
        }
```

**Comment by BendixMa** [comment]
Yeah your right. Didn't test it yesterday evening... 

I'm gonna publish it as version `0.3.5` in the coming days. Thank you!
